### ISSUE TITLE
initialise: TypeError: 'ProjectName' object is not iterable

### ISSUE THREAD

**Issue by alunduil** [alunduil/template.py#21]
# Stack Trace and Command
```
vscode ➜ /workspaces/hypothesis-requests (main) $ poetry run -- initialise
Project name: hypothesis-requests
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 2316, in process_value
    value = self.type_cast_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/core.py", line 2304, in type_cast_value
    return convert(value)
           ^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/types.py", line 82, in __call__
    return self.convert(value, param, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/.venv/lib/python3.11/site-packages/click/types.py", line 177, in convert
    return self.func(value)
           ^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/templatise/project_name.py", line 26, in __init__
    self.package = _package_name(name) if not package_name else package_name
                   ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/hypothesis-requests/templatise/project_name.py", line 31, in _package_name
    for character in name:
TypeError: 'ProjectName' object is not iterable
```

**Comment by alunduil** [comment]
This looks to have been resolved with recent fixes.
